- name: Create runit dir
  file:
    state: 'directory'
    path: '/etc/service/mongod'

- name: Create runit script
  template:
    src: 'runit-script.j2'
    dest: '/etc/service/mongod/run'
    mode: '0755'

- name: Ensure mongodb is up
  wait_for:
    port: '{{ mongodb_net_port }}'
    timeout: '10'